# The following line will download the latest Ubuntu Docker image to use as a foundation for
 # building our own Docker image.
 FROM ubuntu:latest
 RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

 COPY Question.py /Question.py
 COPY Readme.txt /Readme.txt