worker:
  env:
    - name: EXTRA_PIP_PACKAGES
      value: dask-ml tensorflow keras --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_PIP_PACKAGES
      value: dask-ml tensorflow keras --upgrade