apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-container
        image:  pavlosprotopapas/ac295_lecture2:db
        imagePullPolicy: Always
        ports:
        - containerPort: 8081