# The following line will download the latest Ubuntu Docker image to use as a foundation for
# building our own Docker image.
FROM ubuntu:latest
RUN apt-get update; exit 0
RUN apt-get install python -y

COPY Question.py /Question.py
RUN python Question.py